---
title: "ML - Dataset de Phishing"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Ruta de los datos en caso de que requiera

#Cargamos nuestras librerías 
library(ggplot2)
library(dplyr)

library(esquisse)
library(tidymodels)
library(tidyverse)
library(skimr)
library(DataExplorer)
library(ggpubr)
library(univariateML)
library(GGally)
library(doParallel)
library(yardstick)
```


```{r filtro}

StepwiseBack <- function(modelo, link = "logit",  datos){
  
   formula <- as.formula(paste("label ~ ", modelo ))
  
   model <- glm(formula, family = binomial(link = link), data = datos)
   
   #print( summary(model))
   #Haciendolo Backward
   modelo_step <- stats::step(
      object = model,
      direction = "backward",
      scope = list(upper = model, lower = ~1),
      trace = FALSE
  )
    
  return(modelo_step) 
}





```






```{r}
datosRaw <- readRDS( file = "C:/Users/ferna/Documents/PhishML/Data/Procesada/datalimpia.rds")

summary(datosRaw)
```
HasSocialNet, HasCopyrightInfo, HasDescription, NoOfSelfRedirect 

- `DomainLength`
- `IsDomainIP`
- `TLD`
- `TLDLegitimateProb`
- `URLCharProb`
- `TLDLength`
- `NoOfSubDomain`
- `LetterRatioInURL`
- `IsHTTPS`


```{r}

filtroLink <- datosRaw %>%
        dplyr::select( DomainLength, IsDomainIP, TLD, TLDLength,NoOfSubDomain, LetterRatioInURL, IsHTTPS)


interacciones_df <- model.matrix(~ .^2, data = filtroLink)[, -1] %>%  # ^2 = hasta interacciones de orden 2
  as.data.frame()


interacciones_df <- cbind(interacciones_df, label = datosRaw$label)  # Agregando la variable Y al dataframe de interacciones
colnames(interacciones_df) <- gsub(":", "_x_", colnames(interacciones_df))


interacciones_df




```


```{r}
interacciones_df$`TLDorg `
```



```{r}
filtroInteracciones <-  interacciones_df %>%
  dplyr::select(label, `DomainLength_x_IsHTTPS1`, `DomainLength_x_TLDnet `,`DomainLength_x_TLDorg `, `DomainLength_x_TLDOther`, `DomainLength_x_LetterRatioInURL`, `TLDnet _x_LetterRatioInURL`, `TLDorg _x_LetterRatioInURL`,  `TLDOther_x_LetterRatioInURL`, `NoOfSubDomain0_x_LetterRatioInURL`, `NoOfSubDomain1_x_LetterRatioInURL`) %>%
  mutate(
    DomainLength = datosRaw$DomainLength, 
    IsDomainIP = datosRaw$IsDomainIP, 
    TLD = datosRaw$TLD, 
    TLDLength = datosRaw$TLDLength,
    NoOfSubDomain = datosRaw$NoOfSubDomain, 
    LetterRatioInURL = datosRaw$LetterRatioInURL,
    IsHTTPS = datosRaw$IsHTTPS
  )


filtroInteracciones
```




```{r}
StepwiseBack("(.)", link = "logit", filtroInteracciones)
```
TLD

```{r}
# label,DomainLength, HasSocialNet, HasCopyrightInfo

#data <- datosRaw %>% dplyr::select(label,DomainLength, IsDomainIP, TLD, TLDLength,NoOfSubDomain, LetterRatioInURL, IsHTTPS )
data <- interacciones_df %>% dplyr::select(DomainLength_x_IsHTTPS1,  `DomainLength_x_TLDnet `,  DomainLength_x_TLDOther, DomainLength_x_LetterRatioInURL , `TLDnet _x_LetterRatioInURL`, `TLDorg _x_LetterRatioInURL`, TLDOther_x_LetterRatioInURL, NoOfSubDomain1_x_LetterRatioInURL, IsDomainIP1,  TLDLength2, TLDLength3,  NoOfSubDomain0, NoOfSubDomain1, LetterRatioInURL, IsHTTPS1, label
) %>%
  mutate(
    TLD = datosRaw$TLD,
    LetterRatioInURL = datosRaw$LetterRatioInURL,# No
    IsDomainIP = datosRaw$IsDomainIP,
    DomainLength = datosRaw$DomainLength
  )

data
```



```{r}
set.seed(12673)
split <- initial_split(data, prop = 0.8, strata = label)
train_data <- training(split)
test_data  <- testing(split)
```




```{r}
# Modelo
modelo_glm <- logistic_reg(
  mode = "classification",
  penalty = tune(),
  mixture = tune()
) %>%
  set_engine("glmnet")

# Receta
transformer <- recipe(label ~ ., data = train_data) %>%
  step_nzv(all_predictors()) %>%
  step_center(all_numeric_predictors()) %>%
  step_scale(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors())

# Folds de validación cruzada
cv_folds <- vfold_cv(train_data, v = 5, strata = label)

# Workflow
workflow_modelado <- workflow() %>%
  add_recipe(transformer) %>%
  add_model(modelo_glm)

# Grid
hiperpar_grid <- grid_regular(
  penalty(range = c(0, 1)),
  mixture(range = c(0, 1)),
  levels = 10
)

# Tuning
registerDoParallel(cores = parallel::detectCores() - 2)

grid_fit <- tune_grid(
  object    = workflow_modelado,
  resamples = cv_folds,
  metrics   = metric_set(accuracy, sens, yardstick::spec),
  control   = control_resamples(save_pred = TRUE),
  grid      = hiperpar_grid
)

stopImplicitCluster()



```

```{r}
best_params <- select_best(grid_fit, metric = "accuracy")


final_model <- finalize_workflow(
  workflow_modelado,
  best_params
)

final_fit <- last_fit(final_model, split)
collect_metrics(final_fit)





```

```{r}
collect_predictions(final_fit) %>%
  yardstick::f_meas(truth = label, estimate = .pred_class)

library(yardstick)

collect_predictions(final_fit) %>%
  conf_mat(truth = label, estimate = .pred_class) %>%
  summary() %>%
  dplyr::filter(.metric %in% c("ppv", "npv"))



```





